name: workspace
publish_to: none

environment:
  sdk: ^3.10.4

workspace:
  - example
  - packages/ant_design_icons
  - packages/bootstrap_icons
  - packages/generator
  - packages/lucide_icons
  - packages/simple_icons
  - packages/tabler_icons

dependencies:
  generator:

dev_dependencies:
  very_good_analysis: ^10.0.0