name: flutter_icons
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

workspace:
  - example
  - packages/tabler_icons

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  recase: ^4.1.0
  unorm_dart: ^0.3.2
  very_good_analysis: ^10.0.0
  xml: ^6.6.1


flutter:

