name: flutter_icons
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

workspace:
  - example
  - packages/simple_icons
  - packages/tabler_icons

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
