name: lucide_icons
description: "Lucide icons package"
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  generator:

flutter:
  fonts:
    - family: LucideIcons
      fonts:
        - asset: fonts/lucide.ttf