name: tabler_icons
description: "Tabler icons package"
publish_to: none
version: 0.0.1+1
repository: https://github.com/snapsl/flutter_icons
issue_tracker: https://github.com/snapsl/flutter_icons/issues

topics:
  - icons

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: TablerIcons
      fonts:
        - asset: fonts/tabler-icons.ttf
    - family: TablerFilledIcons
      fonts:
        - asset: fonts/tabler-icons-filled.ttf
