name: generator
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  mime: ^2.0.0
  recase: ^4.1.0
  xml: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

